### ISSUE TITLE
Share and cutplane camera fighting

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#1041]
If the page has a current camera hash state, and then the camera is changed, then using the cutplane to setup e.g. a cut-plane, uses the existing camera and the position is reset when the cut-plane is activated.  Modified from Oleg's:

**Setup:** All browsers

**Model Link:**
index.ifc

**Steps to Reproduce:**
- [ ] **Action:** Load Bldrs (has fixed camera in hash)
- [ ] **Action:** Add a cutplane
- [ ] **Action:** Move camera
- [ ] **Action:** Clear cutplanes
- [ ]  **Expected Response:** The camera position remains the same and cutplane (and cutplane removed)
- [ ]  **Actual Response:**  Cutplane is removed, but the camera bounces back to the coordinates captured by the URL

**Comment by pablo-mayrgundter** [comment]
@OlegMoshkovich also bouncing back.. can't repro here

bldrs.ai camera sharing
OSX 14.3.1
  - [x] Brave 1.64.109
  - [x] Safari 17.3.1
  - [x] FF 124

**Comment by OlegMoshkovich** [comment]
Setup: Chrome Version 122.0.6261.94 (Official Build) (x86_64)

Model Link:
https://bldrs.ai/share/v/gh/Swiss-Property-AG/Momentum-Public/main/Momentum.ifc#c:-38.64,12.52,35.4,-5.29,0.94,0.86;

Steps to Reproduce:
- [ ] **Action:** Load the Bldrs
- [ ] **Action:** Load Momentum
- [ ] **Action:** Move the Camera
- [ ] **Action:** Click on Share Control
- [ ] **Response:** Camera coordinated are captured by the URL
- [ ] **Action:** Close the share dialog
- [ ] **Action:** Move the model
- [ ] **Action:** Click on the cutplane control
- [ ] **Action:** Select the plan cutplane
- [ ]  **Expected Response:** The camera position remains the same and cutplane is place along the appropriate axis
- [ ]  **Actual Response:**  The camera bounces back to the coordinates captured by the URL

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter PTAL

**Comment by pablo-mayrgundter** [comment]
Actually happening in Brave too.. i think it's not a share problem but rather cutplane fighting with share camera params

**Comment by pablo-mayrgundter** [comment]
Fixed in https://github.com/bldrs-ai/Share/pull/1108
