### ISSUE TITLE
 Cannot Load Sample Model 

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1061]
When attempting to load a sample model, the error "Cannot load file" is encountered.

Happened 3 times in a row.
Link:
https://www.bldrs.ai/share/v/gh/Swiss-Property-AG/Schneestock-Public/main/ZGRAGGEN.ifc#c:80.66,11.66,-94.06,6.32,2.93,-8.72
Screenshot:
<img width="1396" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/52a053d1-f284-4c1c-ba1e-7c8469ee385b">

<img width="1396" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/71ad4614-5498-4786-bae3-e978af975ae0">

**Comment by pablo-mayrgundter** [comment]
The issue here appears to be the "www." prefix affects auth0 behavior.. will see if adding that to allowed domains in auth0 fixes

**Comment by pablo-mayrgundter** [comment]
Updated our auth0 config and now works for me.

**Comment by OlegMoshkovich** [comment]
ok
