### ISSUE TITLE
Create 100 - Imagine: subsequent screenshot fails

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#1068]
When using the AI render feature, the initial capture of the view is successful and behaves as expected. However, any attempts to capture the view after the first one result in a failure. The AI render does not seem to update or capture the new view correctly on subsequent attempts.

**Comment by pablo-mayrgundter** [comment]
Didn't repro on first checkout.  Here's Brave prod.. will check safari next

1st screen, after render
<img width="455" alt="image" src="https://github.com/bldrs-ai/Share/assets/2480879/21a9e1bf-3464-4d1d-a7df-76d776eb09ff">

2nd time, new prompt
<img width="455" alt="image" src="https://github.com/bldrs-ai/Share/assets/2480879/22cd19ed-e8ee-442a-96c8-f28d9a6052cb">

**Comment by pablo-mayrgundter** [comment]
Same with Safari 17.3.1 and FF 124 on OSX 14.3.1

Oleg, can you repro and document your setup?  Will reassign to you now

**Comment by OlegMoshkovich** [comment]
Steps to Reproduce:
- [ ] **Action:**Load the Bldrs
- [ ] **Action:**Load Momentum
- [ ] **Action:**Click Magic wand
- [ ] **Response:** The correct view is captured
- [ ] **Action:**Close imagine dialog
- [ ] **Action:**Move the camera
- [ ] **Action:**Click Magic wand
- [ ]  **Expect:** The correct view is captured
- [ ]  **Actual:** Previous view is captured by the imagine dialog

https://bldrs.ai/share/v/gh/Swiss-Property-AG/Momentum-Public/main/Momentum.ifc#c:-38.64,12.52,35.4,-5.29,0.94,0.86;

**Comment by pablo-mayrgundter** [comment]
Fixed in #1110
