### ISSUE TITLE
Add git action for lint

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#124]
We currently run yarn lint locally with a pre-commit script.  This should be run on git checks to get that green PR button love.

**Comment by oogali** [comment]
Perhaps the `lint` script shouldn't run eslint with the `--fix` flag, at least when executing within a Github Actions context?

**Comment by pablo-mayrgundter** [comment]
Yeah, I agree.  This was to get us started when we wanted to progressively
change the files we touched.

As discussed, any ideas how to enforce this appreciated.  I'll be reading
up tonight

**Comment by pablo-mayrgundter** [comment]
I'm pretty satisfied with our precommit process checking lint, so closing this.
