### ISSUE TITLE
Section plane button broken

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#130]

**Comment by pablo-mayrgundter** [comment]
But I think it could be useful for desktop for beginners.  Or, get rid of it on desktop

**Comment by shafy** [comment]
What do you mean by this? Hovering over an element and pressing Q seems to display the section plane correctly (but I'm also not experienced with IFC and BIM :D). If you provide more context, I can have a look.

**Comment by OlegMoshkovich** [comment]
Need to get rid of the button on Desktop.

**Comment by shafy** [comment]
Sorry for the dumb question, but where does the section plane button appear? I can't seem to find it. Do you have a screenshot?

**Comment by OlegMoshkovich** [comment]
Currently it only appears on the mobile. 
not a dumb question.

**Comment by pablo-mayrgundter** [comment]
Obsolete.  There's no longer a button, just a key.
