### ISSUE TITLE
Misc: Make properties window adjustable

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#148]
The properties window has a fixed size and some content is not showing. Can we make the size adjustable (by dragging it to the left)?

![image](https://user-images.githubusercontent.com/74647806/158375595-bcca7902-faa1-4319-a49b-53f9aa3545e0.png)

**Comment by pablo-mayrgundter** [comment]
Like this would be very cool:

https://user-images.githubusercontent.com/2480879/214316542-26046fe6-b790-44d8-8f52-d51226f7928a.mov
