### ISSUE TITLE
System: FE: Reload after uploading leads to an error

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#149]
When I upload a model from my local file system and hit refresh, the following error is shown:

![image](https://user-images.githubusercontent.com/74647806/158375823-83e99ec3-1919-4d15-8733-2c0e5f9f3fe6.png)

I believe this is expected behavior, since the model was uploaded manually. Maybe we could just get rid of the error message?

**Comment by pablo-mayrgundter** [comment]
Related to #114, the upload feature needs to be explained as a temporary view.. reloading not supported, but we need to block/warn about that.

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter is this still relevant?
<img width="358" alt="image" src="https://user-images.githubusercontent.com/3433606/185216502-1c76df12-d9ab-418a-8db6-53bc94a86d58.png">
in the disclaimer in bold at the bottom of the dialog, shall we add that reloading a page will lead to an error

**Comment by pablo-mayrgundter** [comment]
I think what we have in the dialog is good, but we need to protect the user from inadvertently reloading as well.
- There's an HTML form/browser interaction thing where the browser knows you have unsaved state and will warn you on reload.  We should add that first.
- Once we have that, we can get of this error modal.
