### ISSUE TITLE
Viewer: CutPlane: Include cut-plane in share link

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#153]
e.g.:
https://bldrs.ai/share/v/gh/jlph92/IfcObjUnity/main/Assets/Ifc%20Sample/Bridges/KIT-Bridge.ifc/1/24#c:42.14,19.82,52.23,-1.23,-5.42,9.1

![image](https://user-images.githubusercontent.com/2480879/158585411-b4926470-da85-4a61-a413-438f09b5b4a8.png)

- [x] UI component menu
- [x] ifc viewer logic
- [x] url logic
- [x] test

**Comment by OlegMoshkovich** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/3433606/183256439-965a83c4-a4d2-4d74-8664-0a3b9840fe90.png">
Creating from the normal and coplanar points is the method we can use since this method is taking in parameters.
Tryin to figure out how to obtain normal and a point form selected element.

**Comment by OlegMoshkovich** [comment]
trying to pass in these parameters.  
v.clipper.createFromNormalAndCoplanarPoint({x: -0, y: -0, z: -1}, {x: -48.462753086897266, y: 17.024952582756676, z: 0}, false)

it is currently failing.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/3433606/183258008-103c031c-38c4-4c4b-bbb4-7d2c2733f8cd.png">

@pablo-mayrgundter can you please take a look when you have a moment.
There are several questions
1. how to obtain a point - I am assuming we would want to use a near by element mesh
2. should the normal be specified by the selected element as well - or input through ui element

there is a guy on ifc.js discord who succeeded in this.
i sent him a message
![Uploading image.png…]()

**Comment by OlegMoshkovich** [comment]
https://github.com/imolinav/ifc-maps/blob/main/src/app/services/ifc/ifc.service.ts

<img width="663" alt="image" src="https://user-images.githubusercontent.com/3433606/183653917-8236ad12-1b5d-4fa4-87ea-94af4752c758.png">

**Comment by pablo-mayrgundter** [comment]
@mkeshavarzi fyi

**Comment by OlegMoshkovich** [comment]
Feature Request.

**Comment by MarkusSteinbrecher** [comment]
it works but only with the predefined cut-plane positions. If I move the cut-plane that is not included in the permalink.
