### ISSUE TITLE
Move site off GHP

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#169]
This is required for handling Google Ads correctly as they don't like the 404 bounce.

I found this for howto setup the server:

https://gist.github.com/mjackson/b5748add2795ce7448a366ae8f8ae3bb

We also need a CD script to update the service on new pushes to main.

**Comment by pablo-mayrgundter** [comment]
👀 https://www.mitrais.com/news-updates/aws-amplify-vs-google-firebase-which-is-better/
Leaning towards Goog, surprise surprise...

**Comment by shafy** [comment]
Probably missing some context here, but I really like [Netfliy](https://www.netlify.com/). They even have a neat feature that builds a preview and links to it for every PR automatically. Or do you want to move away from static hosting?

**Comment by oogali** [comment]
This issue is superseded by #224.
