### ISSUE TITLE
Fix shortcut dialog.

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#175]
Shortcuts dialog is not formatted correctly on Mobile.

**Comment by shafy** [comment]
Just to visualize the issue:

<img width="339" alt="Screenshot 2022-04-29 at 11 25 13" src="https://user-images.githubusercontent.com/1881676/165919150-57edfc8b-7b52-4599-a691-73bd9e109e3f.png">

**Comment by pablo-mayrgundter** [comment]
ping.  looks fixed in prod
