### ISSUE TITLE
Bug: ifc leads to frozen browser screen

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#181]
After loading this model: https://github.com/Swiss-Property-AG/Portfolio/blob/main/seestrasse220413_0.ifc and selecting any element, the browser window freezes (no insights from the browser developer tools).

**Comment by shafy** [comment]
Seems like a performance related issue. If I wait long enough, it does end up loading the model and displaying the file tree (MacBook M1 with Firefox).

**Comment by pablo-mayrgundter** [comment]
Can't repro.  File is no longer serving (project archived) and we have been using Seestrasse as one of our demo models for a long time.
