### ISSUE TITLE
Load model menu has wrong tooltip and icon

### ISSUE THREAD

**Issue by shafy** [bldrs-ai/Share#189]
The load model tooltip reads "Shortcut keys", and the used icon is usually associated with sharing, not opening a file.

<img width="542" alt="Screenshot 2022-04-29 at 11 22 08" src="https://user-images.githubusercontent.com/1881676/165918397-9fc0a6a9-abca-41db-bf75-0962a63f7e68.png">

I suggest using the folder icon that's already used in the modal:

<img width="349" alt="Screenshot 2022-04-29 at 11 23 47" src="https://user-images.githubusercontent.com/1881676/165918490-1e483660-5cb3-4400-adfb-ba6bc4f63a1b.png">

**Comment by pablo-mayrgundter** [comment]
Looks good to me.  @OlegMoshkovich agree?

**Comment by OlegMoshkovich** [comment]
yes sounds good!
change is going out now.

**Comment by shafy** [comment]
Looks like this is deployed. Closing.
