### ISSUE TITLE
System: Enable server-side react-router

### ISSUE THREAD

**Issue by oogali** [bldrs-ai/Share#223]
When using the `BrowserRouter` component of the React Router library, a general issue frequently encountered is if a user takes an application deep link and attempts to pull that up in their browser, they will receive a 404 Not Found error from the serving web server.

The 404s are caused by the web server not knowing that these additional virtual paths are all handled by the same React SPA.

This gap can be solved by configuring the web server appropriately to always return the HTML of the SPA in response to any request for a [valid] route.

Once this is solved, the expected result is that deep linking into BLDRS should no longer raise a 404 Not Found error to the browser.

NB: Dev still uses the 404 bounce, as does cypress, since it has a plain webserver that reads out of the /docs build.  Maybe revisit these later if we move to a direct-serve locally.

- [x] Create Netlify redirect configuration

**Comment by OlegMoshkovich** [comment]
@oogali is this in progress?

**Comment by pablo-mayrgundter** [comment]
This was implemented a long time ago and changed desc to note we still use 404 bounce for cypress and dev.
