### ISSUE TITLE
Open <send-mail> in "Share the model link"  

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#226]
On the Share the model link UI the arrow makes me as a user think I can send this via mail. Actually nothing happens when I click on it. Can we add this feature so I don't have to copy the link manually?

**Comment by pablo-mayrgundter** [comment]
In the dialog that comes up, how about a button with an email icon that when you click it creates a mailto dialog?  This is the web-standard way.. it's a little clunky, but has widespread support

**Comment by MarkusSteinbrecher** [comment]
Users (like Johannes and myself) think the arrow on top is for sending it. Maybe we remove the arrow on top and add the email icon that you propose?

**Comment by pablo-mayrgundter** [comment]
I'm comparing to Google Docs and Figma.  Both have a share button that opens a dialog that helps you invite people from your contacts via email or copy the link.  Is the contacts integration what you're expecting?  If so I agree we should add that, but also wouldn't drop the link.

**Comment by MarkusSteinbrecher** [comment]
Sounds good. And yes, we should have both (keep the link).

**Comment by OlegMoshkovich** [comment]
This is solved in the new layout/design sprint 1 - iteration 1
closing this issue.
