### ISSUE TITLE
Research Matrix/Github Discussion

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#236]
Create a document summarizing the use of GitHub Discussions and matrix to enable chat feature of BLDRS.

**Comment by pablo-mayrgundter** [comment]
[Share Matrix/Element Integration Requirements](https://docs.google.com/document/d/1mjYe4yPvO3iR4UzOYH_lZXxzkm-eypTEKa9P7gFs5Eg/edit#heading=h.sg0qt9skqgfz)
