### ISSUE TITLE
UX: Auto floor-plan views

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#246]
Tracking for Mohammed, like the floorplan viewer at canvas.io https://canvas.io/

Requirements: as a user viewing a model I want an easy way to look at the floor plans. Instead of having to do this manually by navigating the view and aligning the section planes I actually want an icon on the screen that takes me directly to each floor plan.  It would show the levels of the building and if I click one of them, the view moves to floor-plan view - i.e. it puts the camera above the model and cuts the floor at the right level so the floor-plan is visible.

Nice add-on: using arrow-up/arrow-down moves the view directly to one level above/below

**Comment by mkeshavarzi** [comment]
Here's how I would suggest approaching this issue:

With ifctool, given an IFC:

1. Extract the number of floors;
2. Calculate the best z values for a section plane for each floor;
3. Calculate an ideal location for the camera

With Share:

1. Place the camera
3. Have a UI that toggles the section planes.

The extractLevels.js script in ifctool already contains some of the required scripts. I can work on preparing a more specific script for this matter.

**Comment by MarkusSteinbrecher** [comment]
Sounds good. There should be a couple of coordinates that help identifying the z values per floor. There should be a project reference point and probably we can take the z values of each slab. The floors should be in the ifc hierarchy.
There may be some cases where you have "half-levels" i.e. a level that is in between level 1 and level 2.

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter this is a perfect example of a sketch issue, or whatever you want to call it.

**Comment by pablo-mayrgundter** [comment]
Hi Mohammed, could you please link your drafts here and comment on status.  Demo looked great!

**Comment by mkeshavarzi** [comment]
> Hi Mohammed, could you please link your drafts here and comment on status. Demo looked great!

Thanks - Sure. PR opened in #364.

**Comment by mkeshavarzi** [comment]
Two features would need to be implemented:
1. Top camera target position should be located at the center of the model (currently target seems to be (0,0,0);
2. After clicking on the "floorplan view" button, camera should go back to the previous location or default perspective location.

**Comment by mkeshavarzi** [comment]
> Two features would need to be implemented:
> 
> 1. Top camera target position should be located at the center of the model (currently target seems to be (0,0,0);
> 2. After clicking on the "floorplan view" button, camera should go back to the previous location or default perspective location.

Feature (1) has been implemented.

**Comment by mkeshavarzi** [comment]
> Two features would need to be implemented:
> 
> 1. Top camera target position should be located at the center of the model (currently target seems to be (0,0,0);
> 2. After clicking on the "floorplan view" button, camera should go back to the previous location or default perspective location.

Feature (2) is also implemented. The camera animates to an arbitrary location calculated by the center of the IFC model.

**Comment by mkeshavarzi** [comment]
@MarkusSteinbrecher does the current "Isolate Levels/ Toggle View" complete this request?

**Comment by MarkusSteinbrecher** [comment]
Fine for now I feel and we can improve on this version still.
