### ISSUE TITLE
Attach a model to note

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#256]
Add the logic to read the model from the URL specified in the GitHub issue and load the correct model when the Note is activated.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/3433606/178339191-98092179-3d3a-44ec-8bb5-90316d654da9.png">

**Comment by pablo-mayrgundter** [comment]
With my Markdown addition, you can now embed links in the comment that bring you to other models.  Is that sufficient for this use-case?

**Comment by pablo-mayrgundter** [comment]
Heya, you said you cleared your notification queue, so pining this to make it active.

**Comment by pablo-mayrgundter** [comment]
ping

**Comment by OlegMoshkovich** [comment]
ping ping
