### ISSUE TITLE
Rewire notes selection UI.

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#259]
Select a note by clicking on the card.

**Comment by pablo-mayrgundter** [comment]
Looks like it's in your closed board, but also I don't see any action now when I click on a comment.

https://bldrs.ai/share/v/p/index.ifc#i:1148362525::c:-45.81,18.08,112.36,-43.48,15.73,-4.34

clicking on 1 & 2 here doesn't do anything.  Camera works if I click on the camera button.
