### ISSUE TITLE
Bug: Issue loading ifc (from VDE)

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#282]
Loading this [ifc](https://drive.google.com/file/d/13xGLI92SKEhRETJHJMsg7S-KW9_sOkTN/view?usp=sharing), there seem to be a couple of issues:

![image](https://user-images.githubusercontent.com/74647806/181004858-3833dcee-2247-4b99-81cb-4e026e89ec0f.png)

![image](https://user-images.githubusercontent.com/74647806/181004934-94f9d5c6-5f55-4588-aea6-32135909a4aa.png)

**Comment by pablo-mayrgundter** [comment]
Fixed
