### ISSUE TITLE
Include section planes in perma-link

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#284]
As a user of Comments I want to select a model view including section planes, i.e. be able look inside the building and select certain elements.

From first user feedback this is a must-have feature for quality checking models (e.g. scan to BIM workflow).

**Comment by pablo-mayrgundter** [comment]
Yep!  Duplicate of #153. Added to View: Navigate project

**Comment by pablo-mayrgundter** [comment]
Yep!  Duplicate of #153.
