### ISSUE TITLE
Bug: Mobile Keyboard pushes the app screen up

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#296]
When the input field is activated on mobile the app is pushed up with white space visible at the bottom of the screen.

**Comment by pablo-mayrgundter** [comment]
Works for me.. still seeing this?
![image](https://user-images.githubusercontent.com/2480879/188153972-6139eb6f-0da6-48fa-8296-9287c8f22c75.png)

**Comment by OlegMoshkovich** [comment]
oh Iphone this is still relevant.

**Comment by pablo-mayrgundter** [comment]
Ah bummer.  Please add a screen from iPhone

**Comment by OlegMoshkovich** [comment]
this id for safari only.
