### ISSUE TITLE
Notes: Always expand (show more)

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#306]
As a default have the notes expanded (show all) and not truncated like it is at the moment.

**Comment by pablo-mayrgundter** [comment]
Maybe just title for issues list, and when you have a single issue selected, everything is expanded?

**Comment by MarkusSteinbrecher** [comment]
Yes that would work. We need a toggle button at some point and for now I am going to expand them anyway ... so why not just expand them?

**Comment by OlegMoshkovich** [comment]
Notes are expanded by default - show more/less is subtracted from the notes. Closing this issue.
