### ISSUE TITLE
Notes navigation incorrect after reloading

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#315]
Opening the notes and skipping through them from 1/5 to 5/5 works fine. If you are on note 5/5 and reload the page, the display changes to 1/5 although it is still showing note 5/5

![image](https://user-images.githubusercontent.com/74647806/182815686-be839c86-8b72-4abc-8ed0-771040a076dd.png)

**Comment by MarkusSteinbrecher** [comment]
tested here: https://deploy-preview-308--bldrs-share.netlify.app/share/v/gh/Swiss-Property-AG/Astra-Public/main/ASTRA.ifc#i:1328337651::c:67.99,25.75,15.54,17.3,5.44,8.64

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter @MarkusSteinbrecher this has to do with the way we are keeping track of the state - reloading the page is causing the state to clear.

The number count is really nice and adds clarity.
However, dues to the complexity I am going to remove it in this iteration.
<img width="97" alt="image" src="https://user-images.githubusercontent.com/3433606/182825917-5f3fde83-5546-4ba5-afad-964300f38d12.png">

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter unless you know a straightforward way to fix it.

**Comment by pablo-mayrgundter** [comment]
I think storing in the permalink is the right way forward, and made a similar comment in #319.

**Comment by OlegMoshkovich** [comment]
Feature request. 
At the moment the issue is solved by not showing the note number in the controls.

**Comment by MarkusSteinbrecher** [comment]
OK, now it is a feature request

**Comment by OlegMoshkovich** [comment]
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/3433606/183943988-ed2afb6d-e087-48b4-951b-97087ae83791.png">
in the current iteration - the issue is solved by removing the not index from the controls.
