### ISSUE TITLE
Viewer: Hovering over elements is obstructing the view

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#341]
When I look at a floor level (using a cut plane) and move my mouse inside the building, the floor slab is selected and colored. This is obstructing the view and annoying (at least to me). Other tools only highlight elements, when they are double clicked.

![image](https://user-images.githubusercontent.com/74647806/185874596-461a8cdc-63d0-4879-bdf8-49ae3b3e92df.png)

**Comment by OlegMoshkovich** [comment]
fixed in #351
