### ISSUE TITLE
Viewer: Allow Ortho Camera View

### ISSUE THREAD

**Issue by mkeshavarzi** [bldrs-ai/Share#346]
For use cases such as floorplan views, facades, sections, etc, users would require to view the model through an orthographic camera projection instead of a perspective view. Such a feature can show up as a button to toggle between perspective and ortho views with shortcuts to top/down/left/right views

**Comment by mkeshavarzi** [comment]
PR in #364

**Comment by OlegMoshkovich** [comment]
@mkeshavarzi I am closing this issue. since you have achieved the mvp version of this.
