### ISSUE TITLE
System: Changing color scheme causes full reload of IFC model

### ISSUE THREAD

**Issue by oogali** [bldrs-ai/Share#359]
If you are viewing an IFC model and change the color theme from light to dark or vice versa, this action will result in a complete reload of the IFC model (and the pre-requisite IFC.js WASM).

This has implications for performance when dealing with large models, or if someone toggles the theme in the middle of data entry (i.e. they will lose their drafted comment).

**Comment by MarkusSteinbrecher** [comment]
duplicate #156
