### ISSUE TITLE
System: Auth

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#372]
I have the draft PR #360 that I just demo'd and is kinda broken.  Goal there is to get stable login and then do a simple mutating call to github API.  I'm not sure Auth0 auth tokens can be used for GH API.

Follow-on will be to use GHAPI to do full CRUD on issues and comments.

Talked with Ogali, he'll take this.  Thanks O!

**Comment by pablo-mayrgundter** [comment]
Talked through this with @OlegMoshkovich .. I do have an in-flight PR.. @oogali, do you have any work you'd like to track on Auth?

**Comment by pablo-mayrgundter** [comment]
@oo-bldrs opening some new issues.. 

First: https://github.com/bldrs-ai/Share/issues/376

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter @oogali I will close this issue since it is too general, #376 is used to track the current auth work.
