### ISSUE TITLE
VYZN: Viewer: Highlighting of one or more elements by the user.

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#382]
One or more elements of the model can be **highlighted** by the user.

Programmatic access is separately defined in #550.

**Comment by MarkusSteinbrecher** [comment]
@Adrian62D how is this different to #475?

**Comment by Adrian62D** [comment]
#475 is about allowing a user to actually filter through the elements.

In BimCollab this functionality is called SmartViews:
https://www.bimcollab.com/en/products/bimcollab-zoom/smart-views

**Comment by Adrian62D** [comment]
@aozien This can be closed, right?
