### ISSUE TITLE
VYZN: Viewer: UI configuration via Matrix config message

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#391]
Regarding the viewer itself: 
allow to hide or show different UI elements, such as the tree view, the share buttons, the search bar…

Available programmatically via app.

Optional: Let the user customize this if the app allows it.

Fits to product strategy: probably
Estimation: 5

**Comment by pablo-mayrgundter** [comment]
We have been configuring the components on a kind of "scene" basis:
  - open side-drawer and move operation icons when a drawer-based component is active
  - when on mobile, allow toggling of nav tree
  
@MarkusSteinbrecher has proposed a Google Apps-like reveal.  I see this breaking into:
  0. App not visible
  1. Small docked icon, minimal state (e.g. icon with red notifications badge)
  2. Panel, e.g. like current Issues and Properties tools
  3. Full-screen

The benefit of this approach is that the UX interaction between components and apps can be designed to support a few layouts.  I'd compare this to G Apps, Figma.

I'd contrast this with generally configurable UIs like an IDE such as Blender, IntelliJ.  We kinda want to avoid this as UI complexities is one of the key problems in existing AEC desktop tools.

**Comment by Adrian62D** [comment]
@pablo-mayrgundter We'll start working on this. Could you please assign it to me? Thank you.

**Comment by pablo-mayrgundter** [comment]
Moving discussion here from Ibrahim's PR... mostly looks good.  I'm not sure it makes sense to have each button configurable.  Are there any supporting use-cases for turning each one on or off?

Alternatively, how about a single toggle for the entire OperationGroup, or functional subsets that we define here first.

**Comment by Adrian62D** [comment]
The use cases we currently see are as follows:

- cross mark -> to be hidden
- question mark -> sometimes visible / sometimes hidden

<img width="1728" alt="screenshot_2022-12-22_at_09 24 18" src="https://user-images.githubusercontent.com/104829208/209114338-58e30c2c-b219-4a6d-bb32-b78a0d9166d6.png">

So this seems to fit well to the current structure in the UI. This means the controls could be grouped as follows:

- SearchBar
- TreeView
- Collaboration (button group 1)
- ModelInteraction (button group 2)
- Settings (button group 3)

Would this approach be OK for you?
