### ISSUE TITLE
Bug: Scroll bar always visible ... just on my laptop :(

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#401]
![image](https://user-images.githubusercontent.com/74647806/191254197-742c9c22-5eb8-46e8-8fd9-875646d642fa.png)

Chrome: Version 105.0.5195.125 (Offizieller Build) (x86_64)
Mac: 12.6 (21G115)

**Comment by pablo-mayrgundter** [comment]
@MarkusSteinbrecher can you check again.  We did a big refactor.. hopefully this resolved

**Comment by MarkusSteinbrecher** [comment]
Yes, it is gone! Great!

**Comment by pablo-mayrgundter** [comment]
We did fix 2 of the vertical scrollbars, but the third remains elusive.

**Comment by MarkusSteinbrecher** [comment]
The third one is a setting on mac, depending on whether one uses the trackpad or a mouse. I am closing this issue.
