### ISSUE TITLE
Bug: Property Window: some properties are cut at the left

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#402]
![image](https://user-images.githubusercontent.com/74647806/191257586-360448b4-b302-48d9-aaf2-3c49b1a23517.png)

tested with Momentum

**Comment by pablo-mayrgundter** [comment]
Fixed in #395.

**Comment by pablo-mayrgundter** [comment]
Sorry, Markus, can you confirm..

**Comment by MarkusSteinbrecher** [comment]
Yes, looks good!
