### ISSUE TITLE
Viewer: Make sample models dynamic and not hard coded

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#403]
The current sample models we have are hard coded and link to Github Repositories that are not necessarily in our control. The sample models should be selected dynamically through Github search and at least have a check if they still exist. At some point we might even select models from statistics, like top 5 models with most views.

**Comment by pablo-mayrgundter** [comment]
We ended up keeping demo models in our test-models repo.  The idea for search is good but i think already implicit in the search feature UX.
