### ISSUE TITLE
Bug: Text in Notes window is cut at both sides

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#406]
Some users have an issue with notes display:

![image](https://user-images.githubusercontent.com/74647806/192228635-a126a57c-e923-4fe4-9ef5-6e1ea2da053a.png)

Chrome version: Version 105.0.5195.125 (Offizieller Build) (x86_64)

**Comment by pablo-mayrgundter** [comment]
Could you post a link?  Can't reproduce.  Desktop?

**Comment by MarkusSteinbrecher** [comment]
https://bldrs.ai/share/v/gh/Swiss-Property-AG/Turmfalke-Public/main/TURMFALKE.ifc#i:1340200278::c:35.31,67.23,58.84,-2.77,7.81,15.5

Desktop

**Comment by pablo-mayrgundter** [comment]
Markus can repro in Chrome/Safari and FF.

I can't repro in those.

We don't have an IE tester.

**Comment by OlegMoshkovich** [comment]
Look ok for me.

**Comment by MarkusSteinbrecher** [comment]
fixed with #407

**Comment by OlegMoshkovich** [comment]
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/3433606/192374999-c1050607-eb1c-4476-9f0d-3c39daefe5c6.png">

Steps to reproduce - set the chrome default font to small in settings

**Comment by MarkusSteinbrecher** [comment]
Looking good
