### ISSUE TITLE
Viewer: add checkmark to each element in the tree

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#417]
As a user I may want to select or deselect one or multiple elements. For this each element in the tree view has a checkmark that turns its visibility on and off.

See also #384

**Comment by OlegMoshkovich** [comment]
In addition enable selection of multiple elements in the scene using shift+click

**Comment by OlegMoshkovich** [comment]
at the moment it is achieved by shift clicking multiple elements
