### ISSUE TITLE
Bug: Cut plane makes model disappear for Schep; needs to read IFC units from model

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#429]
https://bldrs.ai/share/v/gh/IFCjs/test-ifc-files/main/Schependomlaan/IFC%20Schependomlaan.ifc#c:60.45,-4.32,60.59,1.17,5.93,-3.77

Works for L0 and L1, but higher stories makes model disappear.  I'm guessing this is just incorrect floor finding, as L1 is the whole top of the building.

@mkeshavarzi Can you take this?

There's also still a console log being spit out

<img width="728" alt="image" src="https://user-images.githubusercontent.com/2480879/194589083-d8f3581d-6726-4a3f-a551-7f3ea601cd1c.png">

**Comment by mkeshavarzi** [comment]
@pablo-mayrgundter  - This seems to be an error with the file, where the author has defined levels in which are not used. We may want to filter it, but during one of our all-hands meetings, we decided not to intervene with author mistakes in files.

The console issue is being addressed in #424.

**Comment by mkeshavarzi** [comment]
Addressed in #456.

**Comment by pablo-mayrgundter** [comment]
To clarify what's going on, it's because IFC files have a length unit variable that we ignore.  we assume all units are in meters, but that's just common in IFC.  Schep uses millimeters, so our attempt to split the floors based on their height is way off.

The fix should read the IFC unit element and also include e2e testdata tests that validate with IFC files of different length units.

**Comment by OlegMoshkovich** [comment]
makes sense - Should the title of the issue reflect your comment?

**Comment by pablo-mayrgundter** [comment]
We removed this component, and cutplanes work for this case.
