### ISSUE TITLE
Create an Apps Selector Tool in Toolbar

### ISSUE THREAD

**Issue by stacyvlasits** [bldrs-ai/Share#43]
Users should be able to click on a link to open a tool that performs some function/manipulation on their IFC tile

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter yes absolutely. but not relevant just yet. will close for now.

**Comment by pablo-mayrgundter** [comment]
We moved app planning back to an internal doc.  https://docs.google.com/document/d/1-ecrM_awMI0iwgBZYYjYCEJLCclzVCHgJc1vDY87BiY/edit
