### ISSUE TITLE
Viewer:  Add Navigation Cube

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/Share#442]
Navigation cube is a viewer camera controller that allows the user to quickly switch between basic predefined views.

- Create a three.js navigation cube.
- Place navigation cube in the bottom right corner.
- Add a switch between orthogonal and perspective camera views.

**Comment by OlegMoshkovich** [comment]
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/3433606/196423969-8cc4d52f-98de-46b0-abdc-0915f5e9ca3a.png">
It seem the camera is not aligned between the cube and the model.

**Comment by OlegMoshkovich** [comment]
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/3433606/196424371-59ad575a-2228-401f-8f96-d6a7fd1e569b.png">

when back side of the cube is selected the model zooms in way to close.

**Comment by RyugaRyuzaki** [comment]
1-It seem the camera is not aligned between the cube and the model.
2 -when back side of the cube is selected the model zooms in way to close.
is there a way to control the camera zoom level
=> I found this issue, i did not transform to center of model. 
exam :  back side
           coords.x = -r;=>must be -x+c.x
	   coords.y = c.y;
	   coords.z = c.z;
=> i will fix them now

**Comment by OlegMoshkovich** [comment]
<img width="1440" alt="Screen Shot 2022-10-18 at 3 33 11 PM" src="https://user-images.githubusercontent.com/3433606/196444407-a8cb5c52-0f96-41c7-803c-ef133ae5f95e.png">
<img width="1440" alt="Screen Shot 2022-10-18 at 3 33 09 PM" src="https://user-images.githubusercontent.com/3433606/196444464-f4e11ab7-6af9-4f3b-87d8-a828722ba0d7.png">

Hmm hovering over the face of the cube doe not always selects the surface.

**Comment by RyugaRyuzaki** [comment]
yeah, well, may be i will push z-index of container of cube to highger than main view

**Comment by OlegMoshkovich** [comment]
ah maybe that is it - but that would mean that something in the way and blocking it, not sure that is the problem -- but maybe

**Comment by OlegMoshkovich** [comment]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/3433606/196448704-9048e565-653f-4506-b82e-5c9d71602155.png">

actually you are right - only selection in the green box is allowed -- anything outside of the green box is not registering

**Comment by RyugaRyuzaki** [comment]
@OlegMoshkovich you were right, function raycaster is wrong. i will fix it.

**Comment by OlegMoshkovich** [comment]
awesome!

**Comment by RyugaRyuzaki** [comment]
![issue  zIndex](https://user-images.githubusercontent.com/89787521/196556712-764539b6-ee5a-4663-939d-9049a39eb483.PNG)
 => i found the issue. Because we take zIndex of NavPanel higher than viewer-container
=> so i just change the cube style.zIndex=999=> it works
=> keep fixing the camera and create a toggle button camera change type

**Comment by RyugaRyuzaki** [comment]
=>fixed cast element when client click on buce to change camera
const filterElementClick = _this.scene.children.filter((child) => {
			return child.userData.Element;
		});
and : const intersects = rayCaster.intersectObjects(filterElementClick);
:(( => i try to create a button change camera type, it seems to does not work

**Comment by OlegMoshkovich** [comment]
super cool!

**Comment by OlegMoshkovich** [comment]
Closed PR is here 
https://github.com/bldrs-ai/Share/pull/435
