### ISSUE TITLE
VYZN: As a user I can launch the vyzn app from Bldrs

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#464]
As a user I can launch the vyzn app from Bldrs

**Workflow**

1. Open Bldrs
2. Start vyzn app
3. Vyzn app loads

SSO or loading the proper ifc model is not in the scope here.

**UI** 

When the URL `&appstore=true` is supplied to Bldrs perform the following changes in the UI:

1. Add an app-store icon here in the right panel
2. When clicking the icon the right panel toggles on/off

![image](https://user-images.githubusercontent.com/104829208/220305047-be6a2ed8-5ef2-4830-b48d-ce102912e358.png)

The panel should contain the following content:

![image](https://user-images.githubusercontent.com/104829208/220308058-6e38eea5-a0c8-484d-a343-33d6e32d0c28.png)

https://excalidraw.com/#json=8K9AZSF17N8U6J9hht213,LvzAt9zCXlP4OfI8dgPeVg

Scope:
- Initially use a custom HTML page inside the iframe instead of prod.vyzn.tech
- In Bldrs store the current uploaded file in Local Storage of the browser so that the raw file remains available for vyzn later on. Currently the file is discarded by Bldrs.
- When launching the vyzn applet, transmit the **raw file** through the iframe boundary to the vyzn applet
  - This should be triggered by a Matrix Widget API message
  - If there is a github URL available then transmit the URL as well (the data is discarded at the moment)
- The applet show allow the user to
  - chose a project from a dropdown ("Projekt")
  - chose a building from a dropdown ("Gebäude")
  - hit the button "import"
    - this should close the applet and open vyzn in fullscreen (navigated to project > building) 

The iframe concept has already been explored in a prototype: 

- https://github.com/bldrs-ai/Share/pull/379
- https://deploy-preview-379--bldrs-share.netlify.app/share/v/p/index.ifc#c:-111.37,14.94,90.63,-43.48,15.73,-4.34

This issue should be split later on.

**Comment by Adrian62D** [comment]
Updated description.

**Comment by pablo-mayrgundter** [comment]
Let's do some design discussion here and bring it back when more concrete:
https://discord.com/channels/853953158560743424/1021421673649553528/threads/1077932946687791104
