### ISSUE TITLE
VYZN: As a user I can show/hide spaces (rooms)

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#476]
As a user I can show/hide spaces (rooms)

Part of [BimTool](https://docs.google.com/presentation/d/1hwNEDTwzOExQwTuTr3-DNgs4JD8ijuOHu77AHMpEI20/edit#slide=id.g14aa60b89b7_0_92)

**Comment by OlegMoshkovich** [comment]
reference #384
