### ISSUE TITLE
VYZN: As a user I can undock the vyzn applet in Bldrs to fullscreen

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#480]
As a user I can undock the vyzn applet in Bldrs to fullscreen

Part of [3D-Centric Workflow](https://docs.google.com/presentation/d/1hwNEDTwzOExQwTuTr3-DNgs4JD8ijuOHu77AHMpEI20/edit#slide=id.g14aa60b89b7_0_92)

**Comment by MarkusSteinbrecher** [comment]
To clarify for me: is "undock" the same as "open fullscreen"?

**Comment by Adrian62D** [comment]
Yes, essentially like this button:

![image](https://user-images.githubusercontent.com/104829208/200881869-1e4c0a17-60a2-4fd9-ab6a-0615f855c6df.png)

**Comment by MarkusSteinbrecher** [comment]
as discussed with Adrian, this has to be done in the app - closing this issue
