### ISSUE TITLE
NavTree isn't scrolling 

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#490]
When tree scrolls off the page, I can't gesture scroll down in OSX.  @MarkusSteinbrecher noted this and I think has a mouse wheel.  So probably not an input device thing.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2480879/202440178-9a86bc56-f611-4916-bf97-f4914aecf94f.png">

**Comment by pablo-mayrgundter** [comment]
Related, comment scroll is broken.. will just reuse this bug.

**Comment by MarkusSteinbrecher** [comment]
Scrolling the tree works again. Mobile seems to be broken now. The tree is cut in the middle. And moving the model does only work on the lower part of the screen. If you try it in the middle, the model is not moving (Chrome and Safari). Try loading the homepage on mobile and move the model in the middle.

![image0 (2)](https://user-images.githubusercontent.com/74647806/202515213-edca7948-f4e9-4206-8e32-63804fcc8aad.png)
