### ISSUE TITLE
Bug: Property window moves down when "show all properties" is selected

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#494]
When opening the properties panel and clicking on the "show all properties" radio button the content moves down like this:

![image](https://user-images.githubusercontent.com/74647806/203775389-be4d62c0-976d-4e58-97cc-cda791c921d9.png)

This seems to happen with every model but is worse if the properties content is longer (i.e. moving down further).

**Comment by pablo-mayrgundter** [comment]
Looks like broke in #486:

https://github.com/bldrs-ai/Share/blob/02e2fc31c9516818aa92ec0b525aab2617bd1666/src/Components/SideDrawer.jsx#L65

I replaced the makeStyle css with sx, but that's only supported on Box.

**Comment by pablo-mayrgundter** [comment]
@MarkusSteinbrecher all good?

**Comment by MarkusSteinbrecher** [comment]
Looks good
