### ISSUE TITLE
VYZN: Matrix Widget API: Improve debouncing pattern

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#515]
The current debouncing pattern should be improved as follows:

- Have a single SelectionChanged message instead of selection/deselection
- The SelectionChanged message should be emitted regardless of the trigger
  - Currently the SelectionChanged message is not emitted if the selection was done via message instead of an actual user

**Comment by Adrian62D** [comment]
Will check this proposed design change with Rafael.

**Comment by OlegMoshkovich** [comment]
@Adrian62D please close the issue if completed.

**Comment by Adrian62D** [comment]
@OlegMoshkovich Will be closed by #525.
