### ISSUE TITLE
VYZN: Matrix Widget API: Improve how model-loading is covered in automated tests

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#516]
- Add a new ModelLoaded message that is emitted when the model has been loaded
- From the automated tests, supply a local resource of an .ifc model instead of a network fetch to be independent of the network

**Comment by OlegMoshkovich** [comment]
@Adrian62D please close the issue if completed.

**Comment by Adrian62D** [comment]
@OlegMoshkovich Will be closed by #525.
