### ISSUE TITLE
VYZN: Matrix Widget API: make selection of elements in tests more reliable

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#517]
- Currently the selection of elements in automated tests are based on positions ("center")
- It would be more reliable to perform the selection via the tree-view on the left or other methods
- In order to do this, the opening of the tree-view needs to be guaranteed (currently it does not open up 1 of 5 times)

**Comment by OlegMoshkovich** [comment]
@Adrian62D please close the issue if completed.

**Comment by Adrian62D** [comment]
@OlegMoshkovich Will be closed by #525.
