### ISSUE TITLE
VYZN: Matrix Widget API: Suppress popup during launch

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#539]
Currently, a popup is shown whenever Bldrs is instantiated within an iframe.

The matrix widget API should be enhanced so that this popup can be suppressed.

**Comment by MartinoTschudi** [comment]
@Adrian62D does this refer to the privacy / cookies pop up? 
<img width="331" alt="image" src="https://user-images.githubusercontent.com/87808721/213454911-d72e245c-4a6a-453d-bde9-ab1f797a6fe3.png">

**Comment by Adrian62D** [comment]
Yes, exactly.
