### ISSUE TITLE
MISC: IFC models need to be clipped by multiple planes.

### ISSUE THREAD

**Issue by rondoor124** [bldrs-ai/Share#551]
Looking at the clipping logic of the project, only able to clip the IFC models by one plane, not multiple plane.

https://user-images.githubusercontent.com/92342281/212901784-25892269-0309-40a3-b4e0-76305c18e19c.mp4

I think we need to implement multi plane clipping logic. (e.g. x, y, z, xy, yz, xz, xyz)
Of course, when we press `Q` key several times after selecting the model, the x, y, z planes are applied to the model, but we need additional combination. (yz, xz)

**Comment by OlegMoshkovich** [comment]
@rondoor124 the menu allows for clipping of a single plane because of the link sharing.
Multiple planes can be clipped using Q shortcut.

**Comment by pablo-mayrgundter** [comment]
Hey @OlegMoshkovich I was asking Ron to look at using the CutPlaneControl.

It's underway in #547

**Comment by pablo-mayrgundter** [comment]
Fixed in #547
