### ISSUE TITLE
XYZ app using v0.1 API

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#59]
https://docs.google.com/document/d/1JgLDfkghG6wqyYIplCQisSqyUK2XnRu43UEUEwAe8YI/edit#heading=h.5h9gvbtqsc10

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter close it?

**Comment by pablo-mayrgundter** [comment]
Our App initiative was pushed out and we're now maintaining a doc about this and will do planning there until we're ready for development.  Please ask for access.
