### ISSUE TITLE
Progress indicator when loading a model

### ISSUE THREAD

**Issue by Adrian62D** [bldrs-ai/Share#596]
Currently when loading a new model there is an empty screen shown to the user:

![image](https://user-images.githubusercontent.com/104829208/218436502-4c69542c-9aef-4a1b-b0c6-de54507c33cc.png)

This is especially problematic when the loading takes multiple seconds.

There should be progress indicator at the center of the screen.

**Comment by OlegMoshkovich** [comment]
makes sense.
