### ISSUE TITLE
Github: Loading private model works when copying GH-link but not when forwarding the link

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#637]
We have a privately hosted model that can be viewed in bldrs when copying the gh-link into the search bar:

![image](https://user-images.githubusercontent.com/74647806/221863736-e51d1b49-e827-4589-9638-1b5c18b668d4.png)

but when I share the link I get the following error: 

![image](https://user-images.githubusercontent.com/74647806/221863931-eac7fc55-15a7-4749-bebc-c2a3b02cf2b8.png)

![image](https://user-images.githubusercontent.com/74647806/221863999-01fcf92f-b6ad-4ecd-b0af-fbbaa4157f7f.png)

I am happy to give you access to the Repo but I was able to reproduce the same issue with another model in another private Repo.

Thanks!

**Comment by pablo-mayrgundter** [comment]
Hey O, I lost track and was going to start work on this.. assigning you since you're on it.

**Comment by MarkusSteinbrecher** [comment]
any update on this?

**Comment by OlegMoshkovich** [comment]
@oogali is #630 addressing this issue?

**Comment by pablo-mayrgundter** [comment]
Fixed
