### ISSUE TITLE
Bug: Can't load testModels/seestrasse31_11%20(1).ifc

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#707]
Looks like it's assuming theres a `main` branch.. there's only a `test` branch on that repo.

https://bldrs.ai/share/v/gh/bldrs-ai/testModels/main/seestrasse31_11%20(1).ifc

<img width="664" alt="image" src="https://user-images.githubusercontent.com/2480879/230440532-827e0770-7b11-456f-827f-4fac510d7a91.png">

**Comment by nickcastel50** [comment]
Fixed
