### ISSUE TITLE
Open 100 - Open sample model

### ISSUE THREAD

**Issue by oo-bldrs** [bldrs-ai/Share#757]
As a first time user I would like to quickly understand how to open sample models, or how to access models hosted on GitHub.

# Tasks
* Returning user visits homepage, clicks OpenModelControl
  - [ ] OpenModelDialog appears
  * Click Sample Projects menu
    - [ ] Sample project list appears, including Momentum etc. - Screen
    * Choose one of the projects from the list
      - [ ] Project loads - Screen

Also
- [ ] #755

[Shortcut Story](https://app.shortcut.com/bldrsai/story/531/open-sample-project)

**Comment by pablo-mayrgundter** [comment]
Lost track of this idea.. to have a link from About to Open Sample Model dialog
