### ISSUE TITLE
Load progress indicator interferes with About dialog

### ISSUE THREAD

**Issue by oo-bldrs** [bldrs-ai/Share#783]
When loading a model on a small resolution screen (such as a mobile phone), the loading progress indicator covers the bottom portion of the About dialog.

This prevents the user from being able to click on any dialog buttons until loading has completed.

![image](https://github.com/bldrs-ai/Share/assets/113154043/08628d93-597d-4509-aef2-eab1dc72f712)

**Comment by pablo-mayrgundter** [comment]
Fixed
