### ISSUE TITLE
System: headless screenshot regression testing

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#88]
This appears to help: https://www.npmjs.com/package/jest-transform-css

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter is this addressed by Cypress?

**Comment by pablo-mayrgundter** [comment]
Good q.. found this:
https://docs.cypress.io/guides/tooling/visual-testing#Visual-diff-elements

Looks like there's screenshot testing for individual components and whole page, but we still need to implement the tests in our cypress/... dir

**Comment by OlegMoshkovich** [comment]
Is this addressed by Percy?
