### ISSUE TITLE
Research OPFS file storage structure and metadata

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/Share#924]
Few cases to consider here:
- Local open/local save
- Remote open/local save
- Remote resource changes
- Remote resource admin removal of access ([ogali's old PR](https://github.com/bldrs-ai/Share/pull/630))

If remote is git, then store commit hash in metadata.

When remote is not versioned, maybe we compute the hash.  Same question for local open.

On ACLs: maybe we can maintain separate state from GH to allow orgs to make ACL changes and be able to detect and signal

We're also considering using a web-based git client library. See [Isomorphic-git: Capabilities and Limitations](https://docs.google.com/document/d/1MuGJI1C_OLTCHrSSEud3kUbG0XD9ZHyBpdx_ZhM48hs/edit#heading=h.v6f5o46nbmfm)

**Comment by nickcastel50** [comment]
Github Commit steps:

```
1. convert file blob to base 64
2. Get SHA of latest commit on the branch: octokit.rest.git.getRef
3. get SHA of the tree associated with the latest commit: octokit.rest.git.getCommit
4. create a blob with the base64'd file content: octokit.rest.git.createBlob
5. create a new tree with the base tree and the blob: octokit.rest.git.createTree
6. create a new commit: octokit.rest.git.createCommit
7. update the reference of the branch to point to new commit: octokit.rest.git.updateRef
```
