### ISSUE TITLE
File picker does not filter by organization

### ISSUE THREAD

**Issue by oo-bldrs** [bldrs-ai/Share#952]
When I go to save a model, I interact with the file picker in order to pick an organization, repository, and folder in that order.

However, when I pick an organization, the list of repositories is not filtered down to the selected organization. Instead, it displays all repositories I have access to.

This leads to three situations:

1. If I select a repository that is not part of the selected organization, the resulting URL is incorrect and leads to the application receiving 404s from the GitHub API.

2. The previous error is not handled by the application (or bubbled up to the UI), so the user is unaware that they will be able to perform a successful save.

3. The contents of the "Folder" dropdown don't reflect that the repository contents are unavailable and instead display the default/fallback value of `/` and the "Create a folder" option is not presented.

**Comment by nickcastel50** [comment]
Filtering returned repositories by owner should now be added in the latest netlify for that PR.
