### ISSUE TITLE
URL should change after save to newly saved location

### ISSUE THREAD

**Issue by oo-bldrs** [bldrs-ai/Share#953]
When I save a model to a new location, the browser URL remains at the original URL (currently `/v/new/...` pending #951).

Is my expectation incorrect that after a save, the browser URL and state should reflect the repository and filename I saved to?

**Comment by pablo-mayrgundter** [comment]
Yep, i think dupe of https://github.com/bldrs-ai/Share/issues/949, tho you said it better :)
